version: v1-10-1
runtime: custom
vm: true
api_version: 1

resources:
  cpu: 1
  memory_gb: 3

automatic_scaling:
  min_num_instances: 6
  max_num_instances: 20
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.25

skip_files:
- ^.*/packages.*$
- ^.*\.dart$
- ^\.git/.*$
