name: 'dartpad_server'
version: 0.0.1
description: An experimental repo for a web based interactive Dart tutorial.

author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/dartpad_server
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  analyzer: '>=0.22.4 <0.23.0'
  args: any
  compiler_unsupported: 0.7.3
  grinder: '>=0.6.4 <0.7.0'
  logging: any
  shelf: any
  shelf_route: any
  crypto: any
  appengine: '>=0.2.1 <0.3.0'

dev_dependencies:
  browser: any
  codemirror: any
  unittest: any
  http: any

executables:
  dartpad_server: