name: dart_services
author: Dart Team <misc@dartlang.org>
description: The server backend for a web based interactive Dart service.
homepage: https://github.com/dart-lang/dart-services

environment:
  sdk: '>=2.0.0-dev.64.1 <2.0.0'

dependencies:
  analysis_server_lib: ^0.1.2+2
  appengine: '^0.4.0'
  archive: ^2.0.0
  args: '^1.4.1'
  crypto: ^2.0.0
  front_end: '>=0.1.0-alpha.4.1'
  logging: '>=0.9.0 <0.12.0'
  path: ^1.3.0
  shelf: ^0.7.0
  shelf_cors:
    path: 'third_party/pkg/dart-shelf_cors'
  rpc: '>=0.6.0-dev.0'
  uuid: ^1.0.1
  yaml: ^2.0.0

dev_dependencies:
  _discoveryapis_commons: '>=0.1.0 <0.2.0'
  discoveryapis_generator: ^0.9.8
  async: '>1.13.3'
  codemirror: ^0.4.0
  grinder: ^0.8.0
  http: '>=0.11.1 <0.12.0'
  test: '>=1.2.0'

executables:
  services: null
